name = "Steampunk Co-Op"
author = "SzeMrok, Kacper0510"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f023ff98e8432a2b922d3a0962ca0da5a5a25cccb41646971d1500fedf6f73c1"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
