name = "Steampunk Co-Op"
author = "SzeMrok, Kacper0510"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "128af99933340d7c9e72aa056ab1258216b917b4c5d0946d48e3ad90e40ef7da"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
