name = "Steampunk Co Op"
author = "SzeMrok, Kacper0510"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14255628d8614968d5d12440ad4c91109e4774ab84b615d21bac13f4ec9d7f26"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
