name = "Steampunk Co-op"
author = "SzeMrok, Kacper0510"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d5a434c63064f75ba8369a67d856822f3dd3db433d99aa576a07b0b6013c771"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
