name = "Steampunk Co-op"
author = "SzeMrok, Kacper0510"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0aace62c2f56a82ad2e94f1bed808aaaca49ac1786184a1b873b0a7b503b0704"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
