name = "Steampunk Co-op"
author = "SzeMrok, Kacper0510"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54db4d641b9625c1b8cfa7ee581231ad08a8a50148603067df4392905b5dedc0"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
