enable_system_global_packs = false

[resourcepacks]
required = [
    "global_packs/required_resources/"
]

[datapacks]
required = [
    "global_packs/high_priority_data/",
    "global_packs/required_data/"
]

optional = [
    "global_packs/optional_data/"
]